# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Jeśli używasz msbuild, zmień na Windows

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Change directory to Server
      working-directory: ./Server # Przejście do katalogu Server
      run: echo "Moved to Server directory"
    - name: Restore dependencies
      working-directory: ./Server
      run: dotnet restore
    - name: Build
      working-directory: ./Server
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./Server
      run: dotnet test --no-build --verbosity normal
